### ISSUE TITLE
fiomsg.c

### ISSUE THREAD

**Issue by githubmc** [apiriadmin/APIRI#18]
./fio/src/fioDriver/fiomsg.c includes  linux/atc_spxs.h which is not available in the kernel 2.6.22.

**Comment by gallagjm** [comment]
Refer to the ATC5201 Controller Standard for the definition of this file.

**Comment by dtarico-mccain** [comment]
Since atc_spxs.h is a dependency, and is not vendor-specific, I suggest that it be added to the repo.

**Comment by gallagjm** [comment]
Sounds like a good idea. I'll add with the additions I proposed for the ATC Standard, and fix the FIOAPI code accordingly.

**Comment by dtarico-mccain** [comment]
Excellent, thanks!

**Comment by githubmc** [comment]
resolved.
