### ISSUE TITLE
fiodriver compilation

### ISSUE THREAD

**Issue by ckrinke** [apiriadmin/APIRI#2]
The fiodriver depends on two constants which end up being undefined. These are ATC_SP3S & ATC_SP5S. Although the fiomessage.c file includes atc_spxs.h, which is included, atc_spxs.h does not define these two constants.  The ATC specification defines a second header file for application programs, ATC.h, which defines these two constants as strings, i.e. "/dev/sp5s" when I believe the driver wants an integer such as 3 or 5.

So, it looks like the current atc_spxs.h and ATC.h are inapprpriate for the needs of this driver source. One solution is to put #defines in the source. Another is to update the ATC Specification.

The former is the quick answer, the latter is probably the right answer.

Additionally, it may be appropriate to add to the Makefile some notes on compiling the driver modules and the order of directory compiles to handle this and "order of compilation".

I did use the common out of tree make command for this driver build, which I assume you folks are using as well. That is "make -C <linuxSourceTree> M=$PWD" after defining ARCH & CROSS_COMPILE in the traditional manner.

Charles

**Comment by gallagjm** [comment]
Good points Charles.
The files atc.h and atc_spxs.h are resident in the BSP files from each manufacturer, although they are specified in the ATC standard. The channel definitions used by the kernel-level sdlc driver interface are specified in B.6.2 of the ATC standard, and it would be convenient to have an enumeration or definitions defined for the values. We could propose an enhanced atc_spxs.h to solve this.
We also intend to provide a "build all" top-level makefile.

Mike
--

**Comment by ckrinke** [comment]
Great, Mike. I like the idea of a top level makefile. I compiled the 13 directories in alphabetical order and 4 did not compile at first cut.

I went back, added the two #defines to fiomsg.c after the include of atc_spxs.h like this;
#define ATC_SP3S 3
#define ATC_SP5S 5
and the fiodriver.ko  compiled and insmodded in our 2.6.35.12 kernel using the "make -C <2.6.35.12-tree> M=$PWD" compile line. Additionally front_panel.ko compiled with the same line. Both insmod with no errors.

Also, once I had done a make in both the libfpui and tod directories, both compiles completed in the fpuiexec and SystemConfiguration directories as the forward references were then resolved.

My initial impression is positive and I will next put all the binaries into one directory, probably /home/econolite in our case for testing and see if I can get them to play with each other on the engine board.

**Comment by ckrinke** [comment]
Copied all binaries to a read/write directory, /home/econolite in this test, insmodded the two .ko files, set LD_LIBRARY_OATH for the .so and ran each compiled executable. The most apparent issus is it appears that fpuiexec has a hard-coded library path which perhaps should be sensitive to LD_LIBRARY_PATH instead

-rwxr-xr-x    1 root     root          9153 Jan 10 20:51 AuxSampleApplication
-rwxr-xr-x    1 root     root         66200 Jan 10 20:51 FrontPanelManager
-rwxr-xr-x    1 root     root         27681 Jan 10 20:51 MasterSelection
-rwxr-xr-x    1 root     root         10958 Jan 10 20:51 SampleApplication
-rwxr-xr-x    1 root     root         81946 Jan 10 20:51 atc_sc
-rw-r--r--    1 root     root        597469 Jan 10 20:51 fiodriver.ko
-rwxr-xr-x    1 root     root         21420 Jan 10 20:51 fiotest
-rwxr-xr-x    1 root     root          7934 Jan 10 20:51 fpuiexec
-rw-r--r--    1 root     root          2352 Jan 10 20:51 front_panel
-rw-r--r--    1 root     root        180402 Jan 10 20:51 front_panel.ko
-rwxr-xr-x    1 root     root         45600 Jan 10 20:51 libfio.so
-rwxr-xr-x    1 root     root         38365 Jan 10 20:51 libfpui.so
-rwxr-xr-x    1 root     root         29146 Jan 10 20:51 libtod.so
# 
export LD_LIBRARY_PATH=/home/econolite
//did not do any mknods yet
# ./atc_sc & //ps shows it
# ./AuxSampleApplication ./AuxSampleApplication: opening device (blocking)
# ./fiotest //runs  prints messages
# ./fpuiexec./fpuiexec: error while loading shared libraries: ../libfpui/libfpui.so: cannot open shared object file: No such file or directory
# ./MasterSelection //runs, prints messages, ps shows it
# ./SampleApplication //runs prints messages

**Comment by ckrinke** [comment]
er, sorry about the font thing in mid-air. This was a copy paste, but I did not expect git to have a nervous breakdown
