### ISSUE TITLE
fpui_set_led() not implemented

### ISSUE THREAD

**Issue by ckrinke** [apiriadmin/APIRI#4]
Neither fpui_set_led() nor fpui_get_led() are implemented. here is a proposed implementation for both.
/*
	LED Operators
*/
int fpui_set_led( int fd, int state )
{
  int ledfd;
  char sbuf[16];  

  if( (ledfd = open( "/dev/cpuactive", O_RDWR )) < 0 ) {
    return( fd );
  }

  sprintf( sbuf, "%d", state );
  write( ledfd, sbuf, sizeof( sbuf ) );
  close (ledfd);
  return( 0 );
}

int fpui_get_led( int fd )
{
  //The ATC specification specifies a write only cpuactive
  //so we are returning an error for this function.
  //Recommend this function be removed from the ATCAPI spec
  return( -1 );
}

**Comment by gallagjm** [comment]
The proposed functions do not match the function prototypes or specification of the ATC 5401 Standard, whereby each virtual display has its own distinct value for the cpu led state.
Further, these functions are subject to a proposal to remove them from the API, contained in the contractor proposal document previously submitted.
