### ISSUE TITLE
SampleApplication.c

### ISSUE THREAD

**Issue by ckrinke** [apiriadmin/APIRI#5]
This is a good example, but it would be even better if renamed "SampleApp" so it fits within the 16 character constraints of MasterSelection and /etc/default/fpui.

Additionally, adding as many libfpui.so and libtod.so examples/tests as there are subroutines would allow both an example for reference for engineers seeking to use the ATCAPI and form a first test of functionality.

**Comment by gallagjm** [comment]
Accepted that the SampleApplication should register a name which fits within the limits.
