### ISSUE TITLE
Differences between specification and reference implementation

### ISSUE THREAD

**Issue by ckrinke** [apiriadmin/APIRI#6]
We are discovering some differences between the ATCAPI specification and the reference implementation. For example, the prototype for fpui_read_aux_switch() is different between the spec and the implementation.
It would help if the readme file included all the differences between specification and implementation which forms a type of TODO. Additionally, unimplemented features such as the ATCConfigurationMenu.txt support would benefit from a similar mention in the readme or other documentation file to guide adopters of the ATCAPI.

**Comment by gallagjm** [comment]
The difference mentioned is accounted for by the previously submitted contractor proposal document.
The proposal document could be added to the project repository.

**Comment by ckrinke** [comment]
It would help to have a reference copy of the "contractor proposal document" in this git. Do you mind terribly committing it, sir?
