### ISSUE TITLE
Version titles are a bit ambiguous

### ISSUE THREAD

**Issue by ckrinke** [apiriadmin/APIRI#8]
Recommend changing atc_sc_screen.h where various *_APIV are defined from all saying "API Version ..." to:
#define LINE_0_APIV		"fpui version:                            "
#define LINE_1_APIV		"fpui driver version:                     "
#define LINE_2_APIV		"fio version:                            "
#define LINE_3_APIV		"fio driver version:                     "
#define LINE_4_APIV		"tod version:                            "

to make it easier for the user to understand which version is which.

**Comment by gallagjm** [comment]
This has been covered in the previously submitted contractor proposal document.
