### ISSUE TITLE
/usr/bin/eeprom binary does not exist

### ISSUE THREAD

**Issue by ckrinke** [apiriadmin/APIRI#9]
The atc_sc.c program invokes /usr/bin/eeprom which does not exist. I suggest we describe what this program does in a readme, todo or fixme so others can create one as appropriate for use with the ATCAPI.

**Comment by gallagjm** [comment]
The call to a "/usr/bin/eeprom" utility may be commented or removed. (It is intended to cause the eeprom content to be updated to reflect the current platform hardware prior to display in the UI, but this is likely manufacturer-specific if even possible to achieve dynamically).
